import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { explorerUrl, markdownTable } from "../../addressDocs.js";
import { fixtureDocPath } from "./config.js";
import {
  fuseNames,
  type CommonOptions,
  type FixtureEnvelope,
  type FixtureRunName,
  type FixtureRunState,
} from "./types.js";

const COLUMNS = [
  "Name",
  "Fixture ID",
  "Scenario",
  "Form",
  "Fuses",
  "Route",
  "Expected",
  "v2 state",
  "Tier",
  "Owner",
];

/// Scenario layers as the corpus names them, in the order the document lists
/// them. A layer the corpus adds later still appears, after these.
const LAYER_ORDER = [
  "legacy_anchor",
  "pairwise",
  "selected_three_way",
  "hierarchy",
  "batch",
  "temporal",
  "frontend",
];

/// An address as an explorer link where the chain is known, otherwise plain.
function addressLink(chainId: number, address: string): string {
  const url = explorerUrl(chainId, address);
  return url ? `[${address}](${url})` : address;
}

/// Escape the pipes and newlines that would otherwise break the row. Scenario
/// titles carry backticks and punctuation, which markdown renders as written.
function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

/// What a name is expected to do when it is migrated: succeed, or revert with
/// the error its scenario names.
function expectation(name: FixtureRunName, row: FixtureEnvelope): string {
  if (name.expectedResult !== "revert") return "success";
  const error = row.scenario.execution?.expected_error;
  return error ? `revert: ${error}` : "revert";
}

/// Whether pre-migration reserved this name on v2, and for a name it left
/// alone, the v2 state its scenario needs instead.
function v2State(reserved: boolean, row: FixtureEnvelope): string {
  if (reserved) return "reserved";
  const profile = row.scenario.v2_premigration?.profile;
  return profile ? `kept unreserved (${profile})` : "kept unreserved";
}

/// The corpus document: every seeded name, the scenario it stands for, and the
/// shaping that scenario asked for.
///
/// Built from the run state and the corpus it names rather than from a record
/// written during seeding, so it says what the chain was actually given.
export function renderFixtureMarkdown(
  state: FixtureRunState,
  rows: FixtureEnvelope[],
  opts: {
    namespace: string;
    /// Fixture ids pre-migration reserves on v2, as the reservation split
    /// decides them. Passed in rather than derived here so the document and the
    /// label CSV can never disagree about which names were reserved.
    reserved: ReadonlySet<string>;
    generatedBy?: string;
  },
): string {
  const rowById = new Map(rows.map((row) => [row.fixture_id, row]));
  const reserved = opts.reserved;
  const setAside = state.names.filter((name) => name.setupFailure);

  const byLayer = new Map<string, FixtureRunName[]>();
  for (const name of state.names) {
    const layer = rowById.get(name.fixtureId)?.scenario.layer ?? "unknown";
    byLayer.set(layer, [...(byLayer.get(layer) ?? []), name]);
  }
  const layers = [...byLayer.keys()].sort((a, b) => {
    const rank = (layer: string) => {
      const index = LAYER_ORDER.indexOf(layer);
      return index === -1 ? LAYER_ORDER.length : index;
    };
    return rank(a) - rank(b) || a.localeCompare(b);
  });

  // Aliases that resolve to one account are one owner. A nominated owner wallet
  // collapses owner_a, owner_b and owner_c onto itself, so listing them apart
  // would describe a distinction the chain does not have.
  const byAddress = new Map<string, string[]>();
  for (const [alias, address] of Object.entries(state.actorAddresses)) {
    const key = address.toLowerCase();
    byAddress.set(key, [...(byAddress.get(key) ?? []), alias]);
  }
  const actors = [...byAddress.values()]
    .map((aliases) => ({
      address: state.actorAddresses[aliases[0]],
      aliases: [...aliases].sort((a, b) => a.localeCompare(b)),
    }))
    .sort((a, b) => a.aliases[0].localeCompare(b.aliases[0]));
  // One name per account, so a row names its owner once. The aliases a
  // nominated wallet collapsed are listed together in the owners table, which is
  // where the fact that they are one account belongs.
  const ownerName = new Map(
    actors.flatMap(({ aliases, address }) =>
      aliases
        .map((alias) => [alias, aliases[0]] as const)
        .concat([[address.toLowerCase(), aliases[0]] as const]),
    ),
  );

  const lines: string[] = [
    `# ENSv2 ${opts.namespace} fixture corpus`,
    "",
    `> Auto-generated by ${opts.generatedBy ?? "`bun run migration -- fixture docs`"}. Do not edit by hand.`,
    "",
    "ENSv1 names seeded so the migration runs against realistic v1 state. Each name",
    "stands for one scenario; the table says what that scenario covers and how the",
    "name was shaped for it.",
    "",
    `- **Namespace:** ${opts.namespace}`,
    `- **Chain ID:** ${state.chainId}`,
    `- **Seeded at:** ${state.createdAt}`,
    `- **Names:** ${state.names.length} across ${layers.length} layer(s)`,
    `- **Reserved on v2:** ${reserved.size}`,
    `- **Kept unreserved:** ${state.names.length - reserved.size}`,
    `- **Set aside part-shaped:** ${setAside.length}`,
    `- **Batcher:** ${state.batcher}`,
    `- **Corpus digest:** \`${state.fixtureDigest}\``,
    "",
    "## Owners",
    "",
    markdownTable([
      ["Alias", "Address"],
      ...actors.map(({ aliases, address }) => [
        aliases.join(", "),
        addressLink(state.chainId, address),
      ]),
    ]),
  ];

  if (setAside.length) {
    lines.push(
      "",
      "## Set aside",
      "",
      "A contract refused one of these names' setup calls, so its v1 state is only",
      "part-shaped and the scenario it stands for is not fully established.",
      "",
      markdownTable([
        ["Name", "Refusal"],
        ...setAside.map((name) => [
          cell(name.name),
          cell(name.setupFailure ?? ""),
        ]),
      ]),
    );
  }

  for (const layer of layers) {
    const names = [...(byLayer.get(layer) ?? [])].sort((a, b) =>
      a.fixtureId.localeCompare(b.fixtureId),
    );
    lines.push(
      "",
      `## ${layer} (${names.length})`,
      "",
      markdownTable([
        COLUMNS,
        ...names.map((name) => {
          const row = rowById.get(name.fixtureId);
          return [
            cell(name.name),
            name.fixtureId,
            cell(row?.scenario.title ?? ""),
            name.form,
            name.fuses ? cell(fuseNames(name.fuses)) : "—",
            name.route,
            cell(row ? expectation(name, row) : name.expectedResult),
            cell(row ? v2State(reserved.has(name.fixtureId), row) : ""),
            row?.popularity_tier ?? "",
            ownerName.get(name.ownerAlias) ??
              ownerName.get(name.owner.toLowerCase()) ??
              name.ownerAlias ??
              name.owner,
          ];
        }),
      ]),
    );
  }

  return `${lines.join("\n")}\n`;
}

/// Writes the corpus document beside the deployment's artifacts, and returns
/// where. The namespace directory may not exist yet: contracts are resolved
/// lazily, so a run can reach this point without having read anything from it.
///
/// A run that seeded nothing writes no file and returns null. Seeding a corpus
/// is optional, and a deployment without one should carry no document rather
/// than an empty one claiming it has no names.
export function writeFixtureMarkdown(
  opts: CommonOptions,
  state: FixtureRunState,
  rows: FixtureEnvelope[],
  reserved: ReadonlySet<string>,
  generatedBy?: string,
): string | null {
  if (state.names.length === 0) return null;
  const path = fixtureDocPath(opts);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    renderFixtureMarkdown(state, rows, {
      namespace: opts.deploymentNetwork ?? opts.network,
      reserved,
      generatedBy,
    }),
  );
  return path;
}
